### ISSUE TITLE
Not able to generate refresh Token

### ISSUE THREAD

**Issue by alpeshic** [neverendingqs/oauth2-client-shell#60]
I get "{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"52.20.61.20","port":443}" error when I click Trade In Authorization Code button.

**Comment by neverendingqs** [comment]
@alpeshic - what value do you have for `Authorization Endpoint`?

Some possibilities:

* If you are using https://oauth2-client-shell.herokuapp.com/ and the domain is not publicly accessible, you will need to host a local version of the app
* If you are using a local version of the app, ensure you can reach the domain locally

**Comment by alpeshic** [comment]
I am using https://auth.brightspace.com/oauth2/auth as Authorization Endpoint
and https://auth.brightspace.com/core/connect/token as token endpoint

I am using local version of app with http://localhost:3001

**Comment by neverendingqs** [comment]
Could you confirm you can reach https://auth.brightspace.com in a browser on the same computer and network? It should return a 403 (instead of a 404).

**Comment by alpeshic** [comment]
I am getting 403 - Forbidden: Access is denied. when I try  to reach https://auth.brightspace.com  in browser

**Comment by neverendingqs** [comment]
Any chance your firewall is blocking outbound traffic by node.js?

**Comment by alpeshic** [comment]
I did setup node and npm with proxy settings. I am able to get Authorization code but not refresh token

**Comment by neverendingqs** [comment]
Chatted offline. Looks like there might have been a network firewall blocking the outbound request when making the refresh token grant. Using the hosted version on heroku worked as expected.
